name: Frontend

on:
  push:
    branches: [main, dev/*]
    paths:
      - 'EFTQuestManager-frontend/**'
  pull_request:
      branches: [main, dev/*]
      paths:
          - 'EFTQuestManager-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dependencies
        run: npm install
        working-directory: EFTQuestManager-frontend

      - name: Lint
        run: npm run lint
        working-directory: EFTQuestManager-frontend

      - name: Build
        run: npm run build --prod
        working-directory: EFTQuestManager-frontend

      - name: Test
        run: npm test
        working-directory: EFTQuestManager-frontend

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: EFTQuestManager-frontend/dist/